### ISSUE TITLE
How to Make your API Aware of my SSL CERT

### ISSUE THREAD

**Issue by zaxlofful** [Linux123123/Pterodactyl-Discord-Bot#6]
I am using SSL ACME (local certs) for my internal network.

How can I configure your Egg to use my root_ca.crt bundle as verification (secure standard way) or at the very least make it so that your API ignores the TLS errors.

Error Log:
[2022-01-30 20:05:35]: ERROR Unhandled rejection: FetchError: request to https://[url removed for security]:8080/api/client failed, reason: unable to get local issuer certificate 
FetchError: request to https://[url removed for security]:8080/api/client failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/home/container/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:375:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',

**Comment by Linux123123** [comment]
This project is now archived.
